version: '3.8'
services:
  docker-roonserver:
    container_name: Roon
    environment:
      - TZ=Europe/Paris
      - EARLY_ACCESS=false
    volumes:
      - ./roon-app:/app
      - ./roon-data:/data
     # - <PATH TO MUSIC>:/music:ro
     # - <PATH TO BACKUP>:/backup
    #image: comassky/roon:latest
    image: test
    cap_add:
      - ALL
    network_mode: host
    privileged: true
